server:
    port: 80
    tomcat:
        uri-encoding: utf-8
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.78.164.163:3306/common?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 949118Aa``
    freemarker:
        template-loader-path: classpath:/templates/
        charset: utf-8
        cache: false
        expose-request-attributes: true
        expose-session-attributes: true
        expose-spring-macro-helpers: true
        suffix: .ftl
    redis:
        database: 0
# Redis服务器地址
        host: 101.132.171.214
# Redis服务器连接端口
        port: 6379
# Redis服务器连接密码（默认为空）
        password: 987456
